### PR TITLE
Fix link to respository

### PR DESCRIPTION
**Pull request by FrTerstappen**
The link to the github repository was missing the final 's'. This makes the link on crates.io not work. I think this requires a new release to crates.io

### CODE REVIEW

**Comment by umut-sahin** [comment]
Hi @FrTerstappen, thanks for noticing!

Could you update your commit message to the following please?
```
chore: fix repository url
```
Once it's done, I'll merge the PR, add you as an author, update the version, and make the release.

Btw, I need your email to add you to as an author in [Cargo.toml](https://github.com/umut-sahin/bevy-persistent-windows/blob/473702d0de4f4c03a03a62ba4736bcc787073e1c/Cargo.toml#L10-L12), could you send it?

Thanks!

**Comment by FrTerstappen** [comment]
I think i can not change the commit message form the website and I am only back at a computer in a few days.
Alternatively you can just handle this like a open issue, fix the error yourself and close this pull request. Also no need to add me to the authors for such a minor edit.

**Comment by umut-sahin** [comment]
I'll make the changes myself then. It would have taken me a very long time to realize this, so thanks a lot! If you change your mind, let me know and I'll add you as an author anytime :)

**Comment by umut-sahin** [comment]
(closed by https://github.com/umut-sahin/bevy-persistent-windows/commit/9defd5574c8effcb65f1fe80321227bc551a81e0)

**Pull request closed without merging**
